# -*- coding: utf-8 -*-
"""PRODIGY_GA_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2e8oc-IpChJRtPc69JryGWO8Z7gzd24
"""

!pip install transformers torch -q

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = "Artificial Intelligence is transforming the world by"

result = generator(prompt, max_length=100, num_return_sequences=1)

print(result[0]['generated_text'])